services:
  database:
    container_name: manbangdo-database
    image: postgres:17
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: manbangdo
    ports:
      - "5432:5432"